version: "3.4"

volumes:
  postgres_data:


services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/api:cached
    working_dir: /api
    env_file:
      - .env

  db:
    image: postgres:14.4
    container_name: db
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
