version: "3.4"

volumes:
  postgres_data:


services:
  api:
    container_name: scalestack-api
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/api:cached
    env_file:
      - .env

  db:
    image: postgres:14.4
    container_name: scalestack-db
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  books-lambda:
    container_name: scalestack-lambda
    restart: always
    build:
      context: ./lambda
      dockerfile: Dockerfile
    expose:
      - 8080
    working_dir: /books-lambda
